name: simulation
root: ./
startup_window: status
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - gimbal:
      layout: tiled
      panes:
        - waitForRos; roslaunch mrs_serial gimbal.launch
  - additional:
      layout: tiled
      panes:
        - waitForRos; roslaunch mrs_gimbal_camera mrs_gimbal_camera_topictools.launch
  - rviz:
      layout: tiled
      panes:
        - waitForRos; rviz -d $(rospack find mrs_gimbal_camera)/rviz/gimbal.rviz
  - apriltag_detection:
      layout: tiled
      panes:
        - waitForRos; roslaunch mrs_gimbal_camera mrs_gimbal_camera.launch
